### ISSUE TITLE
Instructions in verification code screen not clear

### ISSUE THREAD

**Issue by JCarlosHidalgoSosa** [CampusDelSaber/hermes#130]
**Describe the bug**
Instructions in verification code don't following project structure.

**To Reproduce**
1. Install Hermes app.
2. Click on "Sign in with Google" button.
3. Enter google credentials by existing account or by input.
4. Select "Administrator" item on selector.
5. Click on "Sign Up" button.
6. The app will display you a screen to enter a verification code.
7. Notify that instruction in screen say that the verification email has been sended to final user, not to hermes.info.app

**Expected behavior**
As a normal user that is sign up first time in application, the instructions in screen aren't clear, because it's says a verification code will be sending to my personal email, but this feature don't work on that way, because the verification code first is sended to hermes.info.app account; once development team is agree that user is able to be an admin, the team must re-send this same email to personal user acocunt, letter must be changed for something like "Development team is processing your requesting, please check your email until you can be admin", change the content of current instruction.

**Screenshots**
![ice_screenshot_20230627-173739](https://github.com/CampusDelSaber/hermes/assets/135620337/a6b7f60b-7f92-42f5-8b39-ca55d6a13b78)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - IDE: 
Android Studio Flamingo | 2022.2.1 Patch 2
Build #AI-222.4459.24.2221.10121639, built on May 12, 2023
Runtime version: 17.0.6+0-b2043.56-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 12

**Smartphone :**
 - Device: Xiaomi POCO F3
 - OS: Android 11

Link to issue on github:  https://github.com/CampusDelSaber/hermes/issues/130 

Link to test run on test lodge (open case no. 2):  https://app.testlodge.com/a/37307/projects/55109/runs/704549?tab=2

Link to issue in taiga:[Instructions in verification code screen not clear - Issue [#466](project/marcel-morales-hermes/t/466) - Hermes (taiga.io)](https://tree.taiga.io/project/marcel-morales-hermes/issue/466)

**Comment by VillalobosGarciaGaby** [comment]
Completion of the Issues.
