### ISSUE TITLE
Missing Error Message for Sign Up/Sign In without Internet Access

### ISSUE THREAD

**Issue by fabianromeroclaros** [CampusDelSaber/hermes#177]
**Describe the bug**
When attempting to sign up or sign in with a Google Account without internet access, the expected error message advising the user to connect to the internet is not displayed.

**To Reproduce**
1. Turn off the Wi-Fi or mobile data of the cell phone.
2. Open the Hermes App.
3. Click on the "Sign in with Google" button.
4. Select any Google account to sign in or sign up.
5. Check if an error message is displayed advising the user to connect to the internet.

**Expected behavior**
An error message should be displayed advising the user to connect to the internet since it is not possible to sign in or sign up without internet access.

**Actual behavior**
It is displayed a message with the text "Wait a moment" but nothing else happens and there is no error adivising user to connect to internet.

**Screenshots**
![screen video](https://github.com/CampusDelSaber/hermes/assets/135616751/8f0a8cb4-2b5b-4d0b-ae5e-6289e945ef22)

**Test Configuration**
- Test suite: Team C
- Test Configuration: Android

**Additional context**
This bug affects the functionality of signing up or signing in with a Google Account when there is no internet access. The error message is crucial for informing the user about the connectivity requirement and guiding them to establish an internet connection for successful authentication.

**Comment by JeferssonCL** [comment]
This bug was solved.

![image](https://github.com/CampusDelSaber/hermes/assets/135620350/f4cc1e18-0ea2-4263-8d87-766ddbaa7b9c)
