### ISSUE TITLE
Natural disaster areas are still displayed on the map when the "Natural Disasters" option is deselected

### ISSUE THREAD

**Issue by jhael-arce-jalafund** [CampusDelSaber/hermes#189]
**Describe the bug**
In the window to select which incidents to show, when we stop selecting the "Natural Disasters" option, the areas with natural disasters should no longer be displayed on the map.
**To Reproduce**
1. Install Hermes
2. Open Hermes.
3. Sing in with an account.
4.-Click on the yellow triangle icon.
5.-Click on the "Display" button.
6.-Select the "Natural Disasters" option.
7.-Click on the "OK" button.
8.-Display on the map the areas where there are natural disasters.
9.-Click on the yellow triangle icon.
10.-Click on the "Display" button.
11.-Unselect the "Natural Disasters" option.
12.-Click on the "OK" button.

**Expected behavior**
By deselecting the "Natural Disasters" option, you should stop displaying areas where there are natural disasters.

**Screenshots**

https://github.com/CampusDelSaber/hermes/assets/135137355/4ef666f5-4e7b-4f84-81d8-b53ca69c1b79

**Smartphone :**
 - OS: Android 10

**Comment by saletG08** [comment]
Related bug: [Natural Disaster](https://github.com/CampusDelSaber/hermes/issues/163)
