### ISSUE TITLE
Style changes do not persist on the map after logging out and returning to the application.

### ISSUE THREAD

**Issue by VillalobosGarciaGaby** [CampusDelSaber/hermes#193]
**_Describe the bug_**

During testing of the Hermes Application on Android, it was discovered that when changing the style, either "Dark" or "Satellite", and when logging out and logging back into the application the map style reverts back to the "default".

**To Reproduce**

1. Start the Hermes application.
2. If you already have an active session, continue with step 3. Log in with your Gmail account by pressing the "Sign in with Google" button and you can choose the "General" function to see the default map directly.
3. The application will open, showing the map of your city.
4. Click on the hamburger menu icon.
5. Click on the "Map Style" button.
6. Click on the "Dark" button and the change will be displayed on the map.
7. Click on the hamburger menu icon.
8. Click the "Log out" button and go back to step 2 until step 3.
9. See if the map is in "Dark" mode.

**Screenshots**
1.
![image](https://github.com/CampusDelSaber/hermes/assets/135712226/446399ad-da83-4f79-999c-cbb31e3aea61)
2.
![image](https://github.com/CampusDelSaber/hermes/assets/135712226/71ce2a99-8b17-450c-a139-483018f801a6)

3.
![image](https://github.com/CampusDelSaber/hermes/assets/135712226/602a254d-6e66-4050-8396-301f73e96dda)

**Expected behavior**

- The program retains the map customization settings after closing and reopening it.
- The previously applied customization settings are still visible when the program is reopened.
- Any modifications made to the map customization are saved and applied correctly upon reopening the program.

**Smartphone:**

- Device:  Google Pixel 4   
- Android API 31  
- Android version 11 or higher  
- Google Play Store Services

**Comment by JuanPabloArequipa** [comment]
This issue was fixed by the pull request: https://github.com/CampusDelSaber/hermes/pull/251 
The develop was fixed by this at commit: https://github.com/CampusDelSaber/hermes/commit/7969c4fc1bb085471da99296228a5e09a5a32081
