### ISSUE TITLE
Application stops when the user selects a filter to mark points of interest without internet connection on the main activity.

### ISSUE THREAD

**Issue by JorgeHB69** [CampusDelSaber/hermes#195]
**Describe the bug**
When the user try to select an filter pre stablish like "restaurants" without internet connection on an pre downloaded map the application stops.

**To Reproduce**
1. Open the app
2. Download an map section on offline mode.
3. Restart the app without internet connection.
4. Navigate to downloaded map.
5. Select an filter (located down the search bar)
6. The application stops.

**Expected behavior**
The application can recollect information about point of interest from the downloaded map, and show this points.

**Screenshots**
![Screenshot_20230629-175939.jpg](https://github.com/CampusDelSaber/hermes/assets/135345090/a5be709b-2430-4cce-9f09-07c144c5f4a0)

**Smartphone: **
 - Device: Tecno Spark 10
 - OS: HiOS V8.6.0 ()
 - Android Version: 12

**Comment by JuanPabloArequipa** [comment]
At the dialog for enabling internet, when pressing on Yes, in the case of my device it redirects to a window that don't have the option to enable internet. It opens "Connection & Sharing", but the options to enable internet are at "Wifi" settings or "Mobile networks"


https://github.com/CampusDelSaber/hermes/assets/135129192/4d354f49-6aa9-4a65-98e4-44ca6424dc54
