### ISSUE TITLE
Decomposed estimation time

### ISSUE THREAD

**Issue by denisgandel** [CampusDelSaber/hermes#198]
**NAME:** Bug report
**ABOUT:** Decomposed estimation time
**ASSIGNEES:** Denis Jorge Gandarillas Delgado

**Describe the bug**
When you view the routes, the time estimate is decomposed, because it first shows you the actual estimate, but then changes to a negative estimate.

**To Reproduce**
1. Login to the application.
2. Register or log in if you have not already done so.
3. Select a point on the map.
4. Select whether you want to run the route from your current position or from another selected position on the map.
5. In case you choose another position, select the starting position on the map.
6. Select "Start".
7. Display the estimated time for each route.

**Expected behavior**
It should show a correct time estimate.

**Screenshots**
![image](https://github.com/CampusDelSaber/hermes/assets/135136502/0ce3ea18-73e2-4b49-a444-19a86a823af7)

**Smartphone:**
 - Device: Realme C11 2021
 - OS: Android
 - Version: 11

**Comment by zrock-dev** [comment]
fixed in PR #221
