### ISSUE TITLE
Incorrect Format of the full name field in Account Information

### ISSUE THREAD

**Issue by leohros** [CampusDelSaber/hermes#209]
**Description**
When I try to edit my account information in the "User Account" section, when editing the "Full Name" field, I can use numbers and line breaks, and letters with accents are not displayed.

**To Reproduce**
1. Open the Hermes application.
2. Login if you are not logged in.
3. Click on the hamburger button on the upper left side to open the menu.
4. Click on the "Account" option from the menu.
5. Click on "Edit information" button.
6. Click on "Full name" text field.
7. Write numbers, line breaks and letters with accents.
8. Click on "Save Information" button.

**Expected behavior**
The text field should only accept letters, and letters with accents should be displayed.

**Screenshots**
![image](https://github.com/CampusDelSaber/hermes/assets/135673157/4f335030-9032-4d90-a0a3-8ce8079914fc)
  
![image](https://github.com/CampusDelSaber/hermes/assets/135673157/7dbf1dc8-8cea-457a-bc4b-20c20d5e8596)

**Smartphone:**
 - Device: Samsung A52
 - OS: Android 13

**Other bugs**
[Similar Bug](https://github.com/CampusDelSaber/hermes/issues/209)

**Comment by JeferssonCL** [comment]
This bug was fixed.

![Selection_092](https://github.com/CampusDelSaber/hermes/assets/135620350/97a372cd-ee17-448a-b607-4f2341d9550d)
