### ISSUE TITLE
Incorrect Format of Username Text Field in Account Information

### ISSUE THREAD

**Issue by leohros** [CampusDelSaber/hermes#213]
**Description**
When I try to edit my account information in the "User Account" section, when editing the "Username" field, I can use line breaks, and letters with accents are not displayed.

**To Reproduce**
1. Open the Hermes application.
2. Login if you are not logged in.
3. Click on the hamburger button on the upper left side to open the menu.
4. Click on the "Account" option from the menu.
5. Click on "Edit information" button.
6. Click on "Username" text field.
7. Write line breaks and letters with accents.
8. Click on "Save Information" button.

**Expected behavior**
The text field should only accept letters, and letters with accents should be displayed.

**Screenshots**
![image](https://github.com/CampusDelSaber/hermes/assets/135673157/d9f44184-6bc9-4ffd-a5d4-6e5c97a122d3)  
![image](https://github.com/CampusDelSaber/hermes/assets/135673157/664940a9-4c71-439b-8b0a-2af21c8b4302)

**Smartphone:**
 - Device: Samsung A52
 - OS: Android 13

**Comment by JeferssonCL** [comment]
This bug was fixed.
![Selection_091](https://github.com/CampusDelSaber/hermes/assets/135620350/03a17e23-1108-4d3f-8d49-609e91388215)
