### ISSUE TITLE
Unsuccessful search attempt after search results not found

### ISSUE THREAD

**Issue by JeferssonCL** [CampusDelSaber/hermes#219]
###  This bug is reproduced sometimes
**Description:**
When conducting a search on the Hermes Web Application and no search results are found for the entered keyword, subsequent search attempts yield unsuccessful results. This issue prevents users from conducting further searches and hinders their ability to find relevant information after an initial unsuccessful search.

**Steps to reproduce:**

1. Open the Hermes app.
2. Click on the "Sign Up" button.
3. Select a Hermes Account.
4. Click on the search text field.
5. Enter a word like 'sasadrxd'. A message that the search was not found will be displayed.
6. Try to find another place.

**Expected result:**
After receiving the "No Results Found" message for an initial search attempt, the search functionality should reset and allow users to conduct new searches with different keywords. The application should return to the default search state, enabling users to continue their search attempts and find relevant information.

**Current result:**
Upon entering a keyword that does not exist in the system, the search results page displays a "No Results Found" message. However, when attempting to perform another search with a different keyword afterward, the search function fails to execute. The application remains stuck on the "No Results Found" page, preventing users from conducting subsequent searches.

**Additional Information:**

- The problem arises when trying to perform a new search after a search not found

**Attachments:**
- Result:

![image](https://github.com/CampusDelSaber/hermes/assets/135620350/20e2a7bc-2b5e-41fa-ad2d-3d5e2aa8a62a)

![image](https://github.com/CampusDelSaber/hermes/assets/135620350/4c741c25-440d-4bd8-a96e-9250ca64c4bb)

![image](https://github.com/CampusDelSaber/hermes/assets/135620350/868db901-c587-412e-bb3a-eb2371e6c1b1)

![image](https://github.com/CampusDelSaber/hermes/assets/135620350/48f2435d-7073-4550-8fc9-f6ccdf044490)

- Linked Logs:

![image](https://github.com/CampusDelSaber/hermes/assets/135620350/75bbbe35-14d9-4533-a729-f4d5b73cd2ec)

**Comment by JorgeHB69** [comment]
I try to reproduce this bug but I can't find the same results, I don't know if someone solved it or is an old bug.
Please talk to me about it

**Comment by Misax148** [comment]
The following bug can only be reproduced when using a fake location in the emulator.
A real location must be used, by your physical device.
This bug cannot be fixed since it deals with emulator problems.
