### ISSUE TITLE
Automatic restart of the application when canceling navigation.

### ISSUE THREAD

**Issue by saletG08** [CampusDelSaber/hermes#232]
**Describe the bug**
When an attempt is made to cancel navigation in the application, an unexpected restart of the application occurs. After confirming the route cancellation, the application abruptly closes and restarts automatically, without displaying an error message or providing a clear reason for this behavior.

**To Reproduce**
1. Open the "Hermes" application 2.
2. Log in or register if you are not registered. 3.
3. Select a point on the map by tapping or clicking on it. 4.
4. Click on the "Navigate" button.
5. See the screen to make the navigation.
6. Click on the "Cancel" button.
7. See that a black screen is given and subsequently sends us to the mada again.

**Expected behavior**
After clicking the "Cancel" button, the navigation details screen should close, without starting the navigation process and also the application should return to the map view, indicating that the navigation process has been successfully cancelled.

**Actual Result:**
After clicking the "Cancel" button, it displays an error message stating "Hermes keeps stopping". and the application restarts. and subsequently sends us to the map.

**Screenshots**
- Step 1
![WhatsApp Image 2023-06-30 at 8 51 38 PM](https://github.com/CampusDelSaber/hermes/assets/135137641/12cd21f0-c994-42ff-9db8-837d4a753c4e)

- Step 2
![image](https://github.com/CampusDelSaber/hermes/assets/135137641/5a3183be-bc36-44df-ac4a-4402cbe75a75)

- Step 3
![image](https://github.com/CampusDelSaber/hermes/assets/135137641/2a0c0c02-0b96-488f-a8e4-3b35a586a0dc)

- Step 4
![image](https://github.com/CampusDelSaber/hermes/assets/135137641/1510cf7c-6f83-4b1e-8cfb-5ef4fea3414f)

**Smartphone:**
Device: Samsung SM-A315G
OS: Android 12
Version 12

**Comment by fabianromeroclaros** [comment]
Pull request
https://github.com/CampusDelSaber/hermes/pull/233
