### ISSUE TITLE
Recalculate Route Button Generates New Route from Incorrect Start Point

### ISSUE THREAD

**Issue by saletG08** [CampusDelSaber/hermes#234]
**Describe the bug**
When using the "Recalculate Route" button in the Hermes app after generating a route from a start point different from the current location and canceling the start navigation, the new route generated does not start from the current location as expected. Instead, it consistently returns the start point of the new route from a different location.

**To Reproduce**
1. Launch the Hermes app.
2. Select a point on the map and click on the "Navigate" button.
3. Click on the "Choose on map" button to set a start point different from the current location by selecting another point on the map.
4. After the route is generated, click on the "Cancel" button.
5. Click on "Recalculate Route" button
6. Observe that the app generates a new route with the updated start point, but it is not from the current location.

**Expected behavior**
The app should recalculate the route based on the new start point, which should be the current location, while maintaining the same destination. The new route should start from the current location.

**Actual Result:**
When using the Hermes app, the "Recalculate Route" button does not generate a new route from the current location as expected. Instead, it consistently generates the route from a start point different from the current location.

**Screenshots**

https://github.com/CampusDelSaber/hermes/assets/135137641/0df5a7f6-5d31-49da-b016-14e894eaa229

Smartphone:
Device: Samsung SM-A315G
OS: Android 12
Version 12

**Comment by fabianromeroclaros** [comment]
Pull request: https://github.com/CampusDelSaber/hermes/pull/239
