### ISSUE TITLE
Route Button Appears When Start Point is the Current Location

### ISSUE THREAD

**Issue by saletG08** [CampusDelSaber/hermes#235]
**Describe the bug**
The Recalculate Route button in the Navigator app erroneously appears even when the start point selected is the current location.

**To Reproduce**
1. Launch the Hermes.
2. Select a point on the map and click on "Navigate" button.
3. Choose the current location as the start point.
4. Click on "Start" button.
5. After the route was generated, click on "cancel" button
6. Observe that the Recalculate Route button becomes visible on the screen, despite the start point being the current location.

**Expected behavior**
The Recalculate Route button should only be displayed when a start point different from the current location is selected. It should not appear when the start point is already set as the current location.

**Screenshots**
![image](https://github.com/CampusDelSaber/hermes/assets/135137641/a3b4fba4-1cfa-439d-b08b-e97e0205369c)

Smartphone:
Device: Samsung SM-A315G
OS: Android 12
Version 12

**Comment by fabianromeroclaros** [comment]
Repeated bug:
https://github.com/CampusDelSaber/hermes/issues/236

**Comment by fabianromeroclaros** [comment]
This pull request solved also this issue
https://github.com/CampusDelSaber/hermes/pull/239
