### ISSUE TITLE
Duplicated incident type buttons after report a natural disaster.

### ISSUE THREAD

**Issue by leohros** [CampusDelSaber/hermes#56]
**Description**  
The incident type buttons are duplicated after report a natural disaster.   

**To Reproduce**  
1. Execute the application. 
2. Press the map, (A menu should be displayed)
3. Press in "Natural Disaster" button
4. Mark 3 points in the map
5. Press in the "accept" button
6. Again, press the map (the menu should be displayed)
7. Press in "Incident" button.
8. The incident type buttons are duplicated.
  
**Expected behavior**  
The Incidents should not be duplicated.
  
**Screenshots**   
![image](https://github.com/CampusDelSaber/hermes/assets/135673157/b4aeecef-c446-46ab-b034-b9d994e21324)
![image](https://github.com/CampusDelSaber/hermes/assets/135673157/e6f0515d-93ac-4977-a1a4-561c69a07ecc)
![image](https://github.com/CampusDelSaber/hermes/assets/135673157/64f20854-6c7c-4b09-adf6-4f49731db137)

  
**Environment:**  
 - OS: Android 13
 - Device: Samsung SM-A525M

**Comment by JCarlosHidalgoSosa** [comment]
Bug solved on branck linked
